import "@/styles/globals.css"

import localFont from "next/font/local"
import { cookies } from "next/headers"

import Providers from "@/lib/providers"

const inter = localFont({
  src: "../fonts/Inter-VariableFont_slnt-wght.ttf",
  variable: "--font-sans",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Providers cookies={cookies().toString()}>{children}</Providers>
      </body>
    </html>
  )
}
